image: conanio/gcc8


stages:
  - build


variables:
  CONAN_CHANNEL: testing
  CONAN_PRINT_RUN_COMMANDS: 1
  CONAN_REMOTES: "https://api.bintray.com/conan/bincrafters/public-conan"
  CONAN_STABLE_BRANCH_PATTERN: '\d+\.\d+(\.\d+[-\w\.]*)?'


build:testing:
  stage: build
  except:
    - /^wip\//
  script:
    - python build.py


build:stable:
  extends: build:testing
  only:
    - tags
  variables:
    CONAN_REFERENCE: "b2-helper/$CI_COMMIT_TAG"
