image: conanio/gcc8


stages:
  - test
  - deploy


variables:
  CONAN_CHANNEL: testing
  CONAN_PRINT_RUN_COMMANDS: 1


.conan-init: &conan-init |
  conan profile new --detect default >/dev/null
  conan profile update settings.compiler.libcxx=libstdc++11 default
  conan profile update settings.cppstd=17 default
  conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan


.base:
  before_script:
    - *conan-init


test:
  extends: .base
  except:
    - /^wip\//
  stage: test
  script:
    - conan create . $CONAN_USERNAME/$CONAN_CHANNEL --build missing
    - test/test.sh


.deploy:
  extends: .base
  script:
    - conan create . $CONAN_USERNAME/$CONAN_CHANNEL --build missing
    - conan remote add upload $CONAN_UPLOAD
    - conan user -p $CONAN_PASSWORD -r upload $CONAN_LOGIN_USERNAME
    - conan upload b2-helper/$PACKAGE_VERSION -r upload -c


deploy:testing:
  extends: .deploy
  only:
    - /^master$/
  stage: deploy
  before_script:
    - *conan-init
    - export PACKAGE_VERSION=$(conan inspect . -a version | cut -d\  -f 2)


deploy:stable:
  extends: .deploy
  only:
    - tags
  stage: deploy
  variables:
    PACKAGE_VERSION: $CI_COMMIT_TAG
    CONAN_CHANNEL: stable
