image: conanio/gcc8


stages:
  - test
  - deploy


variables:
  CONAN_USERNAME: $CI_PROJECT_NAMESPACE
  CONAN_CHANNEL: testing
  UPLOAD_REPO: https://api.bintray.com/conan/grisumbras/conan
  CONAN_PRINT_RUN_COMMANDS: 1


test:
  except:
    - /^wip\//
  stage: test
  before_script:
    - conan profile new --detect default >/dev/null
    - conan profile update settings.compiler.libcxx=libstdc++11 default
    - conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
    - conan remote add upload $UPLOAD_REPO
  script:
    - conan create . $CONAN_USERNAME/$CONAN_CHANNEL --build missing
    - test/test.sh
