name: build

on:
  push:
    branches:
      - '*'
      - '!wip/*'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Pull sources
        uses: actions/checkout@v1

      - name: Configure Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Run CPT
        run: |
          python -m pip install --upgrade pip
          pip install conan_package_tools
          python build.py
        env:
          CONAN_USERNAME: grisumbras
          CONAN_CHANNEL: testing
          CONAN_REMOTES: https://api.bintray.com/conan/bincrafters/public-conan
          CONAN_PRINT_RUN_COMMANDS: 1
