name: ci

on:
  push:
    branches:
      - '*'
      - '!wip/*'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Pull sources
        uses: actions/checkout@v1

      - name: Configure Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Run CPT
        uses: grisumbras/run-cpt@v0.1.0
        env:
          CONAN_REMOTES: https://api.bintray.com/conan/bincrafters/public-conan
